// src/app/head.tsx
import type { Metadata } from "next";

// Defina os metadados aqui
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Head() {
  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by create next app" />
      <title>Create Next App</title>
    </>
  );
}
